version: "3"

services:
   mysql:
     image: mysql
     volumes:
       - wordpress_db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
   wordpress:
     depends_on:
       - mysql
     image: wordpress
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_PASSWORD: wordpress

volumes:
    wordpress_db_data: